name: Publish SimpleCrypto.Standard as Nuget Package
 
on:
  workflow_run:
    workflows: ["SimpleCrypto.Standard CI"]
    branches: [ master ]
    types:
      - completed

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .Net Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build Package
        run: dotnet build --configuration Release --no-restore
      - name: Publish to NuGet
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: SimpleCrypto.Standard/SimpleCrypto.Standard.csproj
          TAG_FORMAT: '*'
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}